### ISSUE TITLE
Only five images per note being stored. All other images lost

### ISSUE THREAD

**Issue by chrissyast** [BoostIO/Boostnote#3348]
# Current behavior

Yesterday I created a note with 7 pasted screenshots. I loaded the note today and 2 of the images are not showing. I found my storage path and there are now only 5 images in the folder. I looked at some of the existing issues but they seem to be related to broken links rather than the actual files disappearing. 

![image](https://user-images.githubusercontent.com/31564153/68375296-82a9fd00-013e-11ea-8003-9c124bcd7006.png)

# Expected behavior

All photos to be saved and rendered

# Steps to reproduce

1. Create a markup note with more than 5 images
2. Restart computer
3. Load note
4. Observe that 

(I created another note to test and again only 5 images were present in the storage path, but they still show after closing Boostnote and opening again, so must stay cached somewhere, but then on restart they are lost)

# Environment

- Version : Version: 0.13.0
Electron: 3.0.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Darwin x64 19.0.0

- OS Version and name : MacOS Catalina 10.15

**Comment by chrissyast** [comment]
@Flexo013 is there anything I can do to help on this? I would like to get involved on open-source projects and I have some experience with Javascript

**Comment by Flexo013** [comment]
Confirmed this issue on Ubuntu 16.04 with Boostnote 0.13.0.
![image](https://user-images.githubusercontent.com/4507015/68763204-2b150100-0618-11ea-9e4f-6686c33c39c3.png)
The sixth unique image does not render, even though the file is present. A restart is required.

@chrissyast  I have very little experience with contributing to the code myself. You could try looking on the wiki to see how you can get involved with development.

For this bug specifically I would look at how images are fetched and rendered. See how it behaves images from elsewhere in the file system, or online images. Maybe see if you can find somewhere within the codebase that might limit it to 5 images.

**Comment by chrissyast** [comment]
> The sixth unique image does not render, even though the file is present. A restart is required.

For me the issue is not the same, the image is **not** in storage.

**Comment by Flexo013** [comment]
I see...

You are right! The file I added was indeed removed from disk; even my cloud sync agrees that the file was deleted.
![image](https://user-images.githubusercontent.com/4507015/68763730-7380ee80-0619-11ea-92cc-1eb988ce9b24.png)

**Comment by degart** [comment]
The same issue on MacOS Mojave 10.14.6 with Boostnote 0.13.0

On inserting screenshots from buffer they showed in the document, but when zooming they already inaccessible (randomly, e.g. 2 pictures from 7 or 1 from 3).
After reloading the document - the previews does not work too.

I am keep the Boostnote storage in the Dropbox directory and was able to recovering deleted attachments via their platform, but this situation is unusable for stable works.

Can this bug fixed with new version Boostnote in January 2020?

**Comment by Flexo013** [comment]
@degart Thanks for the info.

The January 2020 release of Boostnote.next might still have this bug. We can't make any guarantees. Do keep in mind that there are two different Boostnote projects.
- Boostnote, this is the one you are currently using. It has some legacy problems.
- Boostnote.next, this one is yet to be released (and has a [different repo](https://github.com/BoostIO/BoostNote.next/)). This is almost a full rewrite with many long-requested features. This other version will have its own issues.

Boostnote will have a 0.14.0 release hopefully some time this week, and if somebody manages to fix this bug, then it will be released fairly soon.

I understand if this is a tad confusing.

**Comment by Fr3d-P** [comment]
I have the same problem with the MacOS *and* Windows version of Boostnote.
Pasting images works when I do it, and I don't see them sometimes when returning to the note (brokken link icon, empty attachment folder).
It's really annoying for me, because it's screenshots from tests, and I've lost the informations...

**Comment by chrissyast** [comment]
This is still happening for me but I'm currently unable to consistently reproduce this problem.

What I have found out from reading the code is that upon `blur` it calls a method to delete any attachments which are not being used in the markdown. It does this by getting all the filenames in the attachments folder for that note, and compares that list of occurrences of a RegEx `/\/?:storage(\/)?([a-zA-Z0-9]|-)*(\/)([a-zA-Z0-9]|\.)+(\.[a-zA-Z0-9]+)?/g` within the markdown of the note. Any files with names which are not contained in the list are deleted from the file system.

So, for whatever reason, the note gets into a state where the filename in the markdown either doesn't match the regex, or simply isn't in the markdown at all when it hits that method.

Is this repository even still maintained now that there is a new version?

**Comment by arcturus140** [comment]
> Is this repository even still maintained now that there is a new version?

there are issues and pull requests on a daily basis.

**Comment by chrissyast** [comment]
> > Is this repository even still maintained now that there is a new version?
> 
> there are issues and pull requests on a daily basis.

I'll rephrase my question...

Is there much, if any, benefit in looking into issues on this repo, now that there is a [new one](https://github.com/BoostIO/BoostNote.next/) for the new release?

**Comment by chrissyast** [comment]
This morning the behaviour happened when I pasted an image on the bottom line of a note, and then I started typing a new line at the top of the note. By putting some console logs I was able to see that the bottom line was **not** contained in the `markdownContent` argument of the `deleteAttachmentsNotPresentInNote` method, but the new top line **was**.

I can't see where the `markdownContent` argument is passed into the method, as it seems to only be called from `const debouncedDeletionOfAttachments = _.debounce(attachmentManagement.deleteAttachmentsNotPresentInNote, 30000)`

Wherever the `markdownContent` is coming from, I'm guessing that when that method is hit, the number of lines is somehow out of sync with the number of lines actually in the editor, so it misses the last line and hence deems the image not to be present in the note. I have very little knowledge about debounce functions so I'm afraid that's all I can offer at this stage.

@Flexo013 @arcturus140 as contributors, does any of this information help diagnose the problem at all?

**Comment by Flexo013** [comment]
I imagine this will be helpful. Thanks for the research!

**Comment by chrissyast** [comment]
My pleasure. If there's anything else I can do, please let me know.

**Comment by BhupeshRohilla** [comment]
I have faced the similar issue.
I created around 3-4 notes and pasted/drag-and-dropped images in them. Then I check them again and saw images were not loading. I went into the folder and indeed images were not there.
Then I left the folder open and pasted 2nd image in the note and I saw the previous file got deleted.
Here is the screenshot of dev-tools which logs the deletion of the file along with errors of missing images.
![Screenshot 2020-10-02 at 8 06 10 PM](https://user-images.githubusercontent.com/47006379/94937002-a7445b80-04ec-11eb-82ac-54297678aa4e.png)
